const Classes = [
  {
    key: 1,
    label: "Mobile Phone",
    name: "Mobile Phone",
    icon: "phone.png",
    category: ["Electronics"],
    color: ["Black"],
    rating: 5,
    price: 599,
    itemsLeft: 200,
    description: "This item is so awesome."
  },
  {
    key: 2,
    label: "Computer Monitor",
    name: "Computer Monitor",
    icon: "computer.png",
    category: ["Electronics"],
    color: ["Black"],
    rating: 4,
    price: 399,
    itemsLeft: 200,
    description: "This item is so awesome."
  },
  {
    key: 3,
    label: "Book",
    name: "Book",
    icon: "book.png",
    category: ["Books"],
    color: ["Black"],
    rating: 2,
    price: 29.99,
    itemsLeft: 1,
    description: "This item is so awesome."
  },
  {
    key: 4,
    label: "Item Name",
    name: "Item Name",
    icon: "books.png",
    category: ["Books"],
    color: ["Black"],
    rating: 3,
    price: 59.99,
    itemsLeft: 200,
    description: "This item is so awesome."
  },
  {
    key: 5,
    label: "Item Name",
    name: "Item Name",
    icon: "calculator.png",
    category: ["Electronics"],
    color: ["Black"],
    rating: 1,
    price: 99.99,
    itemsLeft: 0,
    description: "This item is so awesome."
  },
  {
    key: 6,
    label: "Item Name",
    name: "Item Name",
    icon: "art.png",
    category: ["School"],
    color: ["Black"],
    rating: 4,
    price: 8,
    itemsLeft: 200,
    description: "This item is so awesome."
  },
  {
    key: 7,
    label: "Item Name",
    name: "Item Name",
    icon: "game.png",
    category: ["Electronics"],
    color: ["Black"],
    rating: 5,
    price: 59.99,
    itemsLeft: 200,
    description: "This item is so awesome."
  },
  {
    key: 8,
    label: "Item Name",
    name: "Item Name",
    icon: "video.png",
    category: ["Electronics"],
    color: ["Black"],
    rating: 1,
    price: 12.99,
    itemsLeft: 200,
    description: "This item is so awesome."
  },
  {
    key: 9,
    label: "Item Name",
    name: "Item Name",
    icon: "glasses.png",
    category: ["Books", "School"],
    color: ["Black"],
    rating: 2,
    price: 9.99,
    itemsLeft: 0,
    description: "This item is so awesome."
  },
  {
    key: 10,
    label: "Item Name",
    name: "Item Name",
    icon: "puzzle.png",
    category: ["Toys"],
    color: ["Black"],
    rating: 3,
    price: 4.99,
    itemsLeft: 6,
    description: "This item is so awesome."
  },
  {
    key: 11,
    label: "Item Name",
    name: "Item Name",
    icon: "robot.png",
    category: ["Electronics", "Toys"],
    color: ["Black"],
    rating: 2,
    price: 80,
    itemsLeft: 6,
    description: "This item is so awesome."
  },
  {
    key: 12,
    label: "Item Name",
    name: "Item Name",
    icon: "laptop.png",
    category: ["Electronics"],
    color: ["Black"],
    rating: 5,
    price: 1100,
    itemsLeft: 200,
    description: "This item is so awesome."
  },
  {
    key: 13,
    label: "Item Name",
    name: "Item Name",
    icon: "vr.png",
    category: ["Electronics", "Toys"],
    color: ["Black"],
    rating: 5,
    price: 599,
    itemsLeft: 200,
    description: "This item is so awesome."
  },
];
module.exports = Classes;
